CREATE TABLE IF NOT EXISTS `kaev_reward_queue` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `request_uuid` CHAR(36) NOT NULL,
    `line_number` SMALLINT UNSIGNED NOT NULL,
    `game_server_id` BIGINT UNSIGNED NOT NULL,
    `source` VARCHAR(64) NOT NULL DEFAULT 'web_inventory',
    `cms_user_id` BIGINT UNSIGNED NOT NULL,
    `account_name` VARCHAR(45) NOT NULL,
    `character_id` BIGINT UNSIGNED NOT NULL,
    `character_name` VARCHAR(190) NOT NULL,
    `item_id` BIGINT UNSIGNED NOT NULL,
    `amount` BIGINT UNSIGNED NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
    `attempts` INT UNSIGNED NOT NULL DEFAULT 0,
    `error_message` VARCHAR(500) NULL,
    `created_at` DATETIME NOT NULL,
    `processing_started_at` DATETIME NULL,
    `processed_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `kaev_reward_queue_request_line_unique` (`request_uuid`, `line_number`),
    KEY `kaev_reward_queue_status_created_index` (`status`, `created_at`),
    KEY `kaev_reward_queue_character_status_index` (`character_id`, `status`),
    KEY `kaev_reward_queue_account_status_index` (`account_name`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
